name: Release Build
on:
  push:
    tags: [*]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
          cache: gradle
      - name: Build
        run: ./gradlew build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            api/build/libs/ktSpigot.jar