name: Release Build
on:
  push:
    tags: ['*']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
          cache: gradle
      - name: Build
        run: ./gradlew build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            api/v1_8/build/libs/ktSpigot-v1_8.jar
            api/v1_9/build/libs/ktSpigot-v1_9.jar
            api/v1_11/build/libs/ktSpigot-v1_11.jar
            api/v1_13/build/libs/ktSpigot-v1_13.jar