name: Test
on:
 - pull_request
 - push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 16
          cache: gradle
      - name: Test
        run: ./gradlew test