name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle
      - name: Wrapper
        run: ./gradlew wrapper
      - name: Lint
        run: ./gradlew lintKotlin
      - name: Test
        run: ./gradlew test